### ISSUE TITLE
XSD not existing 

### ISSUE THREAD

**Issue by razakpm** [mulesoft/ldap-connector#20]
xsd not available in the link http://www.mulesoft.org/schema/mule/ldap/3.3/mule-ldap.xsd which specified in the demo application. is any change in the url or mule not supporting it?

I'm using mule studio3.5 and added ldap connector. but while running demo flow I'm getting error as org.xml.sax.SAXParseException; lineNumber: 10; columnNumber: 122; cvc-complex-type.2.4.a: Invalid content was found starting with element 'ldap:config'.

**Comment by ddossot** [comment]
XSDs are provided within the connector JAR and are not published at their namespace URIs. So you should find the XSD in the JAR.

**Comment by razakpm** [comment]
Almost 2 year old post, I quit trying this , any way thanks for the answer.
